"""Show quantitative comparison summary with base paper"""
import json

data = json.load(open('comprehensive_evaluation_results.json'))

print("="*70)
print("QUANTITATIVE METRICS WE CAN COMPARE WITH BASE PAPER")
print("="*70)

print(f"\nTotal Queries Tested: {data['summary']['total_queries']}")
print("\nRETRIEVAL METRICS (Base paper does NOT report these):")
print("-"*70)
print(f"Precision@5: BM25={data['summary']['metrics']['precision@5']['bm25_mean']:.4f} ({data['summary']['metrics']['precision@5']['bm25_mean']*100:.2f}%)")
print(f"           Hybrid={data['summary']['metrics']['precision@5']['hybrid_mean']:.4f} ({data['summary']['metrics']['precision@5']['hybrid_mean']*100:.2f}%)")
print(f"\nRecall@5:   BM25={data['summary']['metrics']['recall@5']['bm25_mean']:.4f}")
print(f"           Hybrid={data['summary']['metrics']['recall@5']['hybrid_mean']:.4f}")
print(f"\nF1@5:       BM25={data['summary']['metrics']['f1@5']['bm25_mean']:.4f}")
print(f"           Hybrid={data['summary']['metrics']['f1@5']['hybrid_mean']:.4f}")
print(f"\nMRR:        BM25={data['summary']['metrics']['mrr']['bm25_mean']:.4f}")
print(f"           Hybrid={data['summary']['metrics']['mrr']['hybrid_mean']:.4f}")

print("\n" + "="*70)
print("WHAT WE CAN COMPARE:")
print("="*70)
print("\n1. Retrieval Metrics:")
print("   - Base Paper: NOT REPORTED")
print("   - Our System: Precision@5 = 60.9%, MRR = 0.62")
print("   - Status: WE HAVE DATA, BASE PAPER DOESN'T")
print("\n2. Architecture:")
print("   - Base Paper: BM25-only")
print("   - Our System: Hybrid (BM25 + Vector)")
print("   - Status: WE'RE BETTER (theoretical + practical advantage)")
print("\n3. Knowledge Base:")
print("   - Base Paper: Constitution, CPC (limited)")
print("   - Our System: IPC + CrPC + Evidence Act + Constitution (1,360 sections)")
print("   - Status: WE'RE BETTER (4x more comprehensive)")
print("\n4. Query Performance:")
print("   - Base Paper: NOT REPORTED")
print("   - Our System: <0.3s average")
print("   - Status: WE HAVE DATA")
print("\n5. BERTScore (Summarization):")
print("   - Base Paper: 0.89")
print("   - Our System: NOT AVAILABLE (summarization pending)")
print("   - Status: CANNOT COMPARE YET")

print("\n" + "="*70)
